name: Build dfzh plugin

on: [push, workflow_dispatch]

permissions:
  contents: read
  actions: write

jobs:
  build-windows:
    uses: ./.github/workflows/build-plugin-windows.yml
    secrets: inherit
